name: Deployment to server
on: push

jobs:
  deploy_to_server:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to VM
        uses: appleboy/ssh-action@master
        with:
          host: 107.175.94.152
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: cd /root/opencloud-v2 && git pull
