name: Deployment to server
on: push

jobs:
  deploy_to_server:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.USERNAME }}
          username: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: cd /root/opencloud-v2 && git pull
